apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {

        sendfile on;

        upstream user-device-service {
            server localhost:8080;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://user-device-service;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-device-config
data:
  application.properties: |
    spring.main.banner-mode=off

    spring.datasource.url=jdbc:mysql://mysql/Home?useSSL=false
    spring.datasource.username=root
    spring.datasource.password=${DB_PASSWORD}
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver

    # HikariCP settings
    # spring.datasource.hikari.*

    #60 sec
    spring.datasource.hikari.connection-timeout=60000
    # max 5
    spring.datasource.hikari.maximum-pool-size=5

    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

    spring.jpa.hibernate.ddl-auto = validate
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    logging.level.org.hibernate.SQL=DEBUG
    logging.level.org.springframework.transaction=TRACE
    logging.level.org.springframework.jdbc.core=TRACE

    logging.pattern.level=%X{requestData}%5p
    logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

    memcached.cache.servers=cache:11211
    memcached.cache.mode=static
    memcached.cache.expiration=86400