CREATE DATABASE IF NOT EXISTS Home;

USE Home;

CREATE TABLE IF NOT EXISTS User (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS DeviceType (
    type INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(150),
    modelname VARCHAR(100) NOT NULL,
    manufacturer VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Device (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type INT NOT NULL,
    mac VARCHAR(12) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    pinCode INT NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    FOREIGN KEY (type) REFERENCES DeviceType(type)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Binding (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    deviceId INT NOT NULL,
    boundAt DATETIME NOT NULL,
    UNIQUE KEY userId (userId, deviceId),
    FOREIGN KEY (userId) REFERENCES User(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
    FOREIGN KEY (deviceId) REFERENCES Device(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);